buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri("https://maven.nekohasekai.me")
        }
        gradlePluginPortal()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:8.5.0")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22")
        classpath("com.google.dagger:hilt-android-gradle-plugin:2.48")
        classpath("org.jetbrains.kotlin:kotlin-serialization:1.9.22")
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri("https://maven.nekohasekai.me")
        }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
