# -----------------------------
# Gradle Performance Optimized
# -----------------------------

org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -Dfile.encoding=UTF-8

# Enable Gradle caching
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.daemon=true

# AndroidX
android.useAndroidX=true

# Faster R class
android.nonTransitiveRClass=true

# Allow newer compileSdk
android.suppressUnsupportedCompileSdk=36

# Enable incremental dexing
android.enableBuildCache=true
android.enableDexingArtifactTransform=true

# Kotlin optimization
kotlin.code.style=official
kotlin.incremental=true
kotlin.daemon.jvmargs=-Xmx2048m

# Compose optimization
android.compose.compiler.report=true
android.compose.compiler.metrics=true
