pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)   // ← تغییر کلیدی
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "Stkvpn"
include ':app'
